### ISSUE TITLE
[fix-bug] undefined method `[]' for nil:NilClass to raw_info['emails']

### ISSUE THREAD

**Issue by SauloSilva** [joel/omniauth-windowslive#10]
I'm getting that errors when the users are attempting to register using windowslive and the response from oauth does not return any emails.

The mistake on this line:
````ruby
email: raw_info ['email'] ['preferred'] || raw_info ['email'] ['account']
````

`raw_info ['email']` is returned nil.

So did this [pull request](https://github.com/joel/omniauth-windowslive/pull/9/files). 
if it exists email, I analyzed all of types and assign to an array so becoming your email attribute:

````ruby
emails: [
  {'value' => 'foo@bar.com', 'type' => 'account', primary: true},
  {'value' => 'foo@bar.com', 'type' => 'personal'},
  {'value' => 'foo@bar.com', 'type' => 'business'},
  {'value' => 'foo@bar.com', 'type' => 'other'}
]
````

else

````ruby
emails: []
````

I did a few adjustments in the tests for everyone to be executed successfully.

I hope I have contributed to this correction.

**Comment by nileshtrivedi** [comment]
This is a bit off-topic, but what scope should I use if I am interested in getting both email and basic profile details? I tried :scope => 'wl.emails wl.basic' but this only returns the email address and none of the profile info.
