### ISSUE TITLE
Missing redirect_uri parameter in call to https://login.live.com/oauth20_authorize.srf?

### ISSUE THREAD

**Issue by brianvh** [joel/omniauth-windowslive#11]
So, I've just updated my app to the latest 0.0.9 release. While that did correct the error that I had reported, I now find that I'm receiving a new error:

https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The provided value for the input parameter 'redirect_uri' is not valid. The expected value is 'https://login.live.com/oauth20_desktop.srf' or a URL which matches the redirect URI registered for this client application.&state=be483c3bb961a141fc84ed8e993f45fc20e0c5a4d87856aa

This was all in the returned URL, with the %20s replaced with normal spaces. Since I knew I had never set a config value for ```redirect_uri```, I was pretty positive that the client authentication call wasn't including it. I then went looking to see what the MSDS docs said about this parameter.

http://msdn.microsoft.com/en-us/library/hh243649.aspx#authorization_rest

At that location on the above page, the ```redirect_uri``` parameter appears to be required by Microsoft, for WindowsLive Client Authorization. Is the fact that OmniAuth::Strategies::WindowsLive doesn't include/send this parameter just an oversight?

If the fix is simple, I'm happy to wait for another update, but I'm also willing to put the time in to create a PR that includes this fix. Let me know. Thanks.

-Brian

**Comment by rogsmith** [comment]
I am receiving this same error. Any suggestions?

**Comment by rogsmith** [comment]
gem 'omniauth-oauth2', '~> 1.3.1' solves the problem.

**Comment by joel** [comment]
https://github.com/joel/omniauth-windowslive/pull/15

**Comment by Liriel** [comment]
The #15 update works on my machine! 
Thx @joel

**Comment by joel** [comment]
@Liriel version published https://rubygems.org/gems/omniauth-windowslive/versions/0.0.11
